### ISSUE TITLE
OVA for 2.0-Alpha startingwith Yellow state for ES using omnibox

### ISSUE THREAD

**Issue by serjs** [Graylog2/omnibus-graylog2#26]
Hi!

I noticed that OVA box started with yellow state of ES after import and starting instance. I download today latest ova box, after news about 2.0 release.

After some digging of sharding relocation with explain, i noticed that some shared are marked as replica. This is true, because omnibus configure graylog server with
```
# cat /opt/graylog/conf/graylog.conf | grep replica
# How many Elasticsearch shards and replicas should be used per index? Note that this only applies to newly created indices.
elasticsearch_replicas = 1
```
from chef, as i understtand
```
# cat /opt/graylog/embedded/cookbooks/graylog/attributes/default.rb | grep replica
default['graylog']['graylog-server']['elasticsearch_replicas'] = 1
```
https://github.com/Graylog2/omnibus-graylog2/blob/2.0/files/graylog-cookbooks/graylog/attributes/default.rb#L66

If i'm understand correct, default configuration for appliances must set zero replicas.

BTW, reconfigure_as* functions currently under development? Trying to use some of them, receiving errors
```
root@graylog-beta:~# graylog-ctl reconfigure-as-server
(eval):24:in `block (2 levels) in load_files': undefined method `[]=' for nil:NilClass (NoMethodError)
	from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:145:in `call'
	from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:145:in `block in add_command'
	from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/lib/omnibus-ctl.rb:366:in `run'
	from /opt/graylog/embedded/lib/ruby/gems/2.1.0/gems/omnibus-ctl-0.0.7/bin/omnibus-ctl:27:in `<top (required)>'
	from /opt/graylog/embedded/bin/omnibus-ctl:23:in `load'
	from /opt/graylog/embedded/bin/omnibus-ctl:23:in `<main>'
```

**Comment by mariussturm** [comment]
Hi Sergey,
the yellow state is intentional. It basically means: Everything in functional but you could add a second Elasticsearch node to the cluster to improve data integrity.
Of course you can run the cluster without any replica but this is not what people expect from a pre-configured system. This would be fine on a custome installation though.

The `graylog-ctl` are under development like the rest of Graylog, we will fix that with the next alpha and beta releases. If you want to create a cluster with the appliance please use the stable 1.3.3 branch for now.

**Comment by mariussturm** [comment]
This will be fixed in the next alpha!

**Comment by serjs** [comment]
@mariussturm, thank you for info about default config and es states at all in ova releases.
