### ISSUE TITLE
Allow full customisation of the elastic search server location

### ISSUE THREAD

**Issue by michaelwiles** [Graylog2/omnibus-graylog2#55]
From what I can tell... the es_nodes setting in [recipes/graylog-server.rb](https://github.com/Graylog2/omnibus-graylog2/blob/2.3/files/graylog-cookbooks/graylog/recipes/graylog-server.rb) does not allow the customising of the port...

It has: `es_nodes      => $registry.get_es_nodes.map{|x| "#{node['graylog']['graylog-server']['elasticsearch_protocol']}://#{x}:9200"}.join(","),`

It would be great if you could add support for fully customising the es_nodes value (i.e. the whole value) as when running with hosted aws elastic search the location of elasticsearch is set via a url. 

If this url is manually set in graylog.conf and graylog restarted then everything works great but as far as I can tell I am unable to set this value from the graylog-settings.json

I suggest having a elasticsearch_hosts value available to directly set this value.

Thank you very much.

Michael

**Comment by mariussturm** [comment]
In the next beta, you can overwrite the connection string with a change in `/etc/graylog/graylog-settings.json`:

```
"custom_attributes": {
    "graylog-server": {
      "elasticsearch_uri": "http://1.1.1.1:9333,http://2.2.2.2:9333"
    }
  }
```

Run `graylog-ctl reconfigure` afterwards.

Because this is not the intended use of the appliances, there will be no `graylog-ctl` command for this. If you need more customization options please consider an installation based on DEB/RPMs.

ad110f11b10ab587bf0ad3fa78ea822b80d3f433
